### ISSUE TITLE
Connecting to Bugsnag Timeout from Lambda functions?

### ISSUE THREAD

**Issue by cggaurav** [bugsnag/bugsnag-node#119]
There are a 1000+  `register` calls being per second made from a Cloud lambda function and some of them timeout on your side?

```
2017-10-22 14:45:35.179 (-06:00)	a5c3541f-b769-11e7-b614-9506af7ecadd	Bugsnag:  { Error: connect ETIMEDOUT 35.186.205.6:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '35.186.205.6',
  port: 443 }
```

Your status page didn't have any issues currently.

**Comment by bengourley** [comment]
Hi @cggaurav!

I've taken a deeper look into the metrics around the time of your logged example, and per the status page everything seems normal on our end.

You mention 1000+ register calls – `register()` doesn't actually perform any network requests, it configures the notifier. Only `notify()` (manual or automatic) actually makes a request to `notify.bugsnag.com`. `register()` should only be called once per process.

How many timeouts do you get? How many events (errors) are being sent to Bugsnag?

Occasional timeouts are unavoidable (due to networking and the public internet) but should be statistically insignificant compared with the number of succesfully delivered reports.

**Comment by cggaurav** [comment]
Hey @bengourley I realized that this was an issue with Lambda not having access to the internet with my VPC settings!
