### ISSUE TITLE
400 RangeError: Maximum Call Stack size exceeded

### ISSUE THREAD

**Issue by matejkramny** [bugsnag/bugsnag-node#16]
I get this when uploading A file using POST request.

Using latest Express.js

```

var express = require('express')
	, routes = require('./routes')
	, http = require('http')
	, path = require('path')
	, mongoose = require('mongoose')
	, MongoStore = require('connect-mongo')(express)
	, mailer = require('nodemailer')

var bugsnag = require("bugsnag");
bugsnag.register("My API Code")

var app = exports.app = express();

// all environments
app.enable('trust proxy');
app.set('port', process.env.PORT || 3000); // Port
app.set('views', __dirname + '/views');
app.set('view engine', 'jade'); // Templating engine
app.set('view cache', true); // Cache views
app.set('app version', '0.0.2'); // App version
app.locals.pretty = process.env.NODE_ENV != 'production' // Pretty HTML outside production mode

app.use(bugsnag.requestHandler); // UnCommenting this line causes RangeError
app.use(express.logger('dev')); // Pretty log
app.use(express.limit('25mb')); // File upload limit
app.use("/", express.static(path.join(__dirname, 'public'))); // serve static files
app.use(express.bodyParser()); // Parse the request body
app.use(express.cookieParser()); // Parse cookies from header
app.use(express.methodOverride());
app.use(express.session({ // Session store
	secret: "mysecret",
	store: sessionStore,
	cookie: {
		maxAge: 604800000 // 7 days in s * 10^3
	}
}));
app.use(express.csrf()); // csrf protection

// development only
if ('development' == app.get('env')) {
	app.use(express.errorHandler()); // Let xpress handle errors
	app.set('view cache', false); // Tell Jade not to cache views
}

var server = http.createServer(app)
server.listen(app.get('port'), function(){
	console.log('Express server listening on port ' + app.get('port'));
});

// routes
//routes.router(app);

app.use(bugsnag.errorHandler);

```

Am I doing something wrong?

**Comment by justinklemm** [comment]
I'm seeing this issue as well. It happens when a file is uploaded through a POST request and Nginx is being used as a reverse proxy. I don't see the issue locally when I access the Node.js app directly on port 3000. But on staging, where Nginx proxies port 80 to the Node app, the RangeError appears.

I'm using Node v0.10.33, but I don't think that's the issue here. I believe BugSnag's Express request handler `app.use(bugsnag.requestHandler)` is going into some kind of infinite callback loop in this scenario that's exhausting the stack.

**Comment by matejkramny** [comment]
@justin uncommenting the app.use fixes this for me, although you lose some
reporting such as request info

**Comment by justinklemm** [comment]
@matejkramny Thanks, yea, commenting out that line prevents the issue for me too. I can deal with the lost info.

It's probably worth Bugsnag digging into this though. It look me a little while to track down the issue and it's particularly "dangerous" because the bug seemingly only occurs when a reverse proxy is used (which can mean that things will work fine during local development, then break in production).

**Comment by snmaynard** [comment]
Yeah - we have left the issue open as it's one that is hard to reproduce. With this nginx lead though we might be able to track it down! Hopefully I'll get some time soon to take a deeper look. Thanks!

**Comment by justinklemm** [comment]
Cool, let me know if I can do anything to help.

You should be able to reproduce it if you setup a simple Express app with a POST route, at say localhost:3000. Then setup Nginx to forward some local domain (ex: http://express.localhost) to it using [ngx_http_upstream_module](http://nginx.org/en/docs/http/ngx_http_upstream_module.html). If you setup an HTML form with a `input[type="file"]` element and POST to the app's route (through Nginx), you should see it.

**Comment by emadd** [comment]
+1

**Comment by ConradIrwin** [comment]
I'm trying and failing to replicate this using https://github.com/ConradIrwin/express-eg. I'd love for one of you to take a look and see if you can make it fail.

**Comment by xiaoshimimi** [comment]
Hi, just curious, is this problem finally be resolve? 

I encountered a same weird problem, and I cannot debug the core reason. and the scenario is very similar with this issue. I hope I can get some inspiration with how this issue got fixed.

**Comment by justinklemm** [comment]
I ended up just disabling `app.use(bugsnag.requestHandler)` and relying on only `app.use(bugsnag.errorHandler)`. This was pretty long time ago and it was while using ExpressJS v3. We've since upgraded to ExpressJS v4. We still have the code commented out because we rarely see any issues where it's necessary. I've been curious as to whether the v4 upgrade fixed it -- but haven't tested.
