### ISSUE TITLE
Question: Can this be used for an isomorphic app?

### ISSUE THREAD

**Issue by benwigley** [bugsnag/bugsnag-node#86]
We are building a react app that runs on the server and the client. Just wondering if this package is able to be run in the browser? Or if not do you have any recommendations for how that could be achieved.

Thanks for your time to help me out.

**Comment by eanakashima** [comment]
@benwigley it's best to only use this library server-side, and bundle in the [bugsnag-js](https://github.com/bugsnag/bugsnag-js) notifier library in the browser. Both are available as npm packages. You could probably theoretically adapt this one to run in a browser environment, but the types of metadata the two collect are quite different. For example, bugsnag-js will collect data about DOM events (like what the user clicked on right before an error), and the browser type, version, and OS that reported the error.

You'll probably also want to set up two different projects in the Bugsnag dashboard — one with the node project type, and the other with the js project type, since the two project types show different fields.

Hope that helps.

**Comment by benwigley** [comment]
@eanakashima thank you, that helps a lot.
