### ISSUE TITLE
requestData is undefined with `POST` requests

### ISSUE THREAD

**Issue by Grmiade** [bugsnag/bugsnag-node#99]
With `POST` requests, `bugsnag.requestData` becomes `undefined` :/ Normal?
I have this error: `Cannot set property 'user' of undefined`. My node version is 7.9.0

`console.log(req.method, bugsnag.requestData === undefined, req.user._id)`
<img width="306" alt="capture d ecran 2017-05-03 a 22 36 42" src="https://cloud.githubusercontent.com/assets/11244106/25680411/0bc6627a-3051-11e7-9813-71fa0db5eb0d.png">

**Comment by kattrali** [comment]
Thanks for the report, @Grmiade. After some testing, this issue seems to be unrelated to the HTTP method but rather to the active [domain](https://nodejs.org/api/domain.html) changing, as is the case if the error is triggered by an unhandled promise rejection or other event emitter. (I have an example of promise rejection specifically [here](https://gist.github.com/kattrali/1ac8dcb209fcd5b5db2e5e16afafae60))

In Node v8.0.0, [promises run in the domain which call them](https://nodejs.org/api/domain.html#domain_domains_and_promises), though the implementation does not provide a way to capture that domain externally without wrapping the promise, and even then, `domain.active` is unset. The correct solution would be to remove the reliance on domains, though this probably will need to wait for the stabilization of [async hooks](https://nodejs.org/api/async_hooks.html) or similar to handle asynchronous resource-specific data.

Looking into this further.

**Comment by Fjandin** [comment]
Would it be an idea to have some sort of fallback where you can set the requestData on the request object itself?

**Comment by bengourley** [comment]
Hey @Grmiade have you had a chance to try Node v8 yet? As @kattrali mentioned, the native promises there should behave in a slightly better way (if indeed you were using promises).

Unfortunately there's not a lot we can do here… domains are fundamentally flawed (which is why they have been deprecated) in ways such as this, but there isn't a direct replacement yet for the features that they provide. We continue to watch this space and will be doing some of our own investigation with async hooks. For the near future at least we just have to stick with the current implementation, which is better than not using domains at all!

In response to your suggestion @Fjandin… yes it is possible to set request data on the `req` object, however the difficulty is that in an error triggered by that req/res handler (in a future tick on the event loop) there is no reference back to `req` – which is why the information is attached to the current `domain`, which _is_ available (except when it isn't 😞 ).

I could have misunderstood your suggestion however! If you do see a way of doing this, if you could sketch it out in a [gist](https://gist.github.com/) or something, that'd be great!

Closing this off as unfortunately I don't see anything we can do at present.
